# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

logger:
  default: info
  logs:
    homeassistant.components.cloud: debug

lovelace:
  mode: yaml
  resources:
    - url: /local/guided-energy-config-card.js
      type: module
  dashboards:
    energy-config:
      mode: yaml
      title: Energy-Config
      icon: mdi:script
      show_in_sidebar: true
      filename: ui-lovelace-config.yaml